# Generated by Django 2.2.2 on 2021-07-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=3)),
                ('timestamp', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=40)),
                ('currency', models.CharField(max_length=40)),
                ('fx_rate_hq', models.CharField(max_length=20)),
                ('fx_rate_spread', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=20)),
                ('branch_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
