# Generated by Django 2.2.2 on 2021-07-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=40)),
                ('address_line2', models.CharField(max_length=40)),
                ('address_line3', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('rate', models.FloatField()),
                ('spread', models.FloatField()),
            ],
            options={
                'db_table': 'rates',
            },
        ),
    ]
